name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: qt And other dependencies...
      run: |
         sudo apt-get update -y
         sudo apt-get install libboost-all-dev -y
         sudo apt-get install libfontconfig dbus libx11-6 libx11-xcb1 libxcb1 -y
         wget http://download.qt.io/official_releases/qt/5.14/5.14.1/qt-opensource-linux-x64-5.14.1.run
         chmod +x qt-opensource-linux-x64-5.14.1.run
         sudo apt-get install libxkbcommon-x11-0 -y
         sudo apt-get install build-essential -y
         sudo apt-get install libfontconfig1 -y
         sudo apt-get install mesa-common-dev -y
         sudo apt-get install libglu1-mesa-dev -y
         ./qt-opensource-linux-x64-5.14.1.run --platform minimal
#     - name: scip
#       run: |
    - name: cmake
      run: mkdir build && cd build && cmake ..
    - name: make
      run: make
#     - name: make check
#       run: make check
#     - name: make distcheck
#       run: make distcheck
