name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: qt
      run: |
         wget http://download.qt.io/official_releases/qt/5.14/5.14.1/qt-opensource-linux-x64-5.14.1.run
         chmod +x qt-opensource-linux-x64-5.14.1.run
         sudo apt6get install libxkbcommon-x11-0
         sudo apt-get install build-essential
         sudo apt-get install libfontconfig1
         sudo apt-get install mesa-common-dev
         sudo apt-get install libglu1-mesa-dev -y
         ./qt-opensource-linux-x64-5.14.1.run
#     - name: scip
#       run: |
    - name: cmake
      run: mkdir build && cd build && cmake ..
    - name: make
      run: make
#     - name: make check
#       run: make check
#     - name: make distcheck
#       run: make distcheck
