name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: qt And other dependencies...
      run: |
         sudo apt-get update -y
         sudo apt-get install libboost-all-dev -y
         sudo apt-get install libfontconfig libdbus-1-3 dbus libx11-6 libx11-xcb1 libxcb1 python3 python3-pip  python3-setuptools -y
         sudo apt-get install libxkbcommon-x11-0 -y
         sudo apt-get install build-essential -y
         sudo apt-get install libfontconfig1 -y
         sudo apt-get install mesa-common-dev -y
         sudo apt-get install libglu1-mesa-dev -y
         sudo pip3 install cuteci && cuteci --rm --installer http://download.qt.io/official_releases/qt/5.12/5.12.2/qt-opensource-linux-x64-5.12.2.run install --destdir /opt/Qt --packages qt.qt5.5122.gcc_64
#         wget http://download.qt.io/official_releases/online_installers/qt-unified-linux-x64-online.run
#         chmod +x qt-unified-linux-x64-online.run
#         sudo ./qt-unified-linux-x64-online.run --platform minimal
#     - name: scip
#       run: |
    - name: cmake
      run: mkdir build && cd build && cmake ..
    - name: make
      run: make
#     - name: make check
#       run: make check
#     - name: make distcheck
#       run: make distcheck
