name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: qt
      run: |
         wget http://download.qt.io/official_releases/qt/5.7/5.7.0/qt-opensource-linux-x64-5.7.0.run
         chmod +x qt-opensource-linux-x64-5.7.0.run
         ./qt-opensource-linux-x64-5.7.0.run
         sudo apt-get install build-essential
         sudo apt-get install libfontconfig1
         sudo apt-get install mesa-common-dev
         sudo apt-get install libglu1-mesa-dev -y
#     - name: scip
#       run: |
    - name: cmake
      run: mkdir build && cd build && cmake ..
    - name: make
      run: make
#     - name: make check
#       run: make check
#     - name: make distcheck
#       run: make distcheck
